version: '2.0'
services:
  proxy:
    image: ertdfgcb/fecproxy
    ports:
    - "80:80"
    depends_on:
    - description
    - reservation
    - reviews
  description:
    image: ertdfgcb/feccomponent
    ports:
    - "3000:3000"
    expose:
    - "3000"
    depends_on:
    - mongo
  reservation:
    image: wpark95/fec
    expose:
    - "3001"
    depends_on:
    - mongo
  reviews:
    image: jzhengcode/fec-reviews-component_web
    expose:
    - "3002"
    depends_on:
    - mongo
  mongo:
    image: mongo
    expose:
    - "27017"